spring.datasource.url=jdbc:mysql://localhost:3308/si_chamados?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=si_chamados
spring.datasource.password=troque-esta-senha
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
